# Generated by Django 4.2.6 on 2024-04-28 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_candidate_current_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Temporary', 'Temporary')], max_length=20)),
                ('role', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('photo', models.ImageField(upload_to='job_photos/')),
                ('contact_number', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
                ('salary', models.DecimalField(decimal_places=0, max_digits=7)),
                ('vacancy', models.PositiveIntegerField()),
                ('published', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Any', 'Any'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Any', max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.category')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recruiter')),
            ],
        ),
    ]
