# Generated by Django 4.2.6 on 2024-04-29 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_location_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='details',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
