# Generated by Django 4.2.6 on 2024-04-26 04:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(25)])),
                ('phone_number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('tenure', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='recruiter_photos/')),
                ('company_name', models.CharField(max_length=100)),
                ('company_phone_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('established_year', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(36), django.core.validators.MinValueValidator(16)])),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('skills', models.TextField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('current_company', models.CharField(default='None', max_length=100)),
                ('current_role', models.CharField(default='None', max_length=100)),
                ('resume', models.FileField(upload_to='candidate_resumes/')),
                ('photo', models.ImageField(upload_to='candidate_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
