# Generated by Django 4.2.6 on 2024-04-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_candidate_age_remove_recruiter_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='years_of_experience',
            new_name='experience_on_field',
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio_link',
            field=models.URLField(blank=True),
        ),
    ]
