# Generated by Django 4.2.6 on 2024-04-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_years_of_experience_candidate_experience_on_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_role',
            field=models.CharField(max_length=100),
        ),
    ]
