# Generated by Django 4.2.6 on 2024-04-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_candidate_experience_on_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience_on_field',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='tenure',
            field=models.PositiveIntegerField(),
        ),
    ]
