# Generated by Django 4.2.6 on 2024-04-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Recruiter', 'Recruiter'), ('Candidate', 'Candidate'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
